name: isometrik_chat_flutter_example
description: Demonstrates how to use the isometrik_chat_flutter plugin.
version: 1.0.1

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  isometrik_chat_flutter:
    path: ../
  device_info_plus: ^11.2.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  path_provider: ^2.1.5
  url_strategy: ^0.3.0
  flutter_svg: ^2.0.17
  timezone: ^0.10.0

dependency_overrides:
  collection: ^1.19.1
  device_info_plus: ^11.2.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
